services:
  mysql: 
    image: mysql:9.1
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_panel
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    networks:
      - frontend-network
      - backend-network
  
  wordpress:
    image: bitnami/wordpress:latest
    container_name: wordpress_app
    restart: always
    depends_on: 
      - mysql
    environment:
      - WORDPRESS_DATABASE_HOST=mysql
      - WORDPRESS_DATABASE_USER=${MYSQL_USER}
      - WORDPRESS_DATABASE_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DATABASE_PASSWORD=${MYSQL_PASSWORD} # profe faltaba el password
      - WORDPRESS_BLOG_NAME=${WORDPRESS_BLOG_NAME}
      - WORDPRESS_USERNAME=${WORDPRESS_USERNAME}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - WORDPRESS_EMAIL=${WORDPRESS_EMAIL}

    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    ports:
      - "8080:8080"
    networks:
      - frontend-network
      - backend-network

  

  https-portal:
    image: steveltn/https-portal:1
    container_name: https_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "${DOMAIN} -> http://wordpress:8080"
      STAGE: 'staging' # Cambiar a 'staging' durante pruebas para evitar bloqueos de Let's Encrypt
    volumes:
      - ssl_certs_data:/var/lib/https-portal
    networks:
      - frontend-network

volumes: 
  mysql_data:
  wordpress_data:
  ssl_certs_data:

networks:
  backend-network:
    driver: bridge 
  frontend-network:
    driver: bridge